import { CHANNELS } from '../config/constants.js';

/**
 * Response Formatter — adapts the AI's raw text response
 * for different output channels (chat, email, WhatsApp, etc.).
 */

/**
 * Format a response for the given channel.
 * @param {string} text - Raw AI response text.
 * @param {string} channel - One of CHANNELS values.
 * @param {object} metadata - Extra data (e.g. attachments, quick replies).
 * @returns {object} Formatted response payload.
 */
export function formatResponse(text, channel = CHANNELS.API, metadata = {}) {
  switch (channel) {
    case CHANNELS.LIVE_CHAT:
      return formatForLiveChat(text, metadata);
    case CHANNELS.EMAIL:
      return formatForEmail(text, metadata);
    case CHANNELS.WHATSAPP:
      return formatForWhatsApp(text, metadata);
    default:
      return formatForApi(text, metadata);
  }
}

/**
 * API / Webhook — clean JSON response.
 */
function formatForApi(text, metadata) {
  return {
    type: 'text',
    message: text.trim(),
    timestamp: new Date().toISOString(),
    ...metadata,
  };
}

/**
 * Live Chat — split long responses into digestible chunks,
 * add quick reply suggestions where appropriate.
 */
function formatForLiveChat(text, metadata) {
  const chunks = splitIntoChunks(text, 500);

  return {
    type: 'chat',
    messages: chunks.map(chunk => ({
      text: chunk.trim(),
      timestamp: new Date().toISOString(),
    })),
    quickReplies: metadata.quickReplies || [],
    typing: false,
  };
}

/**
 * Email — wrap in basic HTML structure.
 */
function formatForEmail(text, metadata) {
  const htmlBody = text
    .split('\n\n')
    .map(p => `<p>${escapeHtml(p).replace(/\n/g, '<br>')}</p>`)
    .join('\n');

  return {
    type: 'email',
    subject: metadata.subject || 'Re: Your inquiry',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: #f8f9fa; border-radius: 8px; padding: 24px;">
          ${htmlBody}
        </div>
        <p style="color: #888; font-size: 12px; margin-top: 16px;">
          This response was generated by our AI support assistant. 
          If you need further help, please reply to this email.
        </p>
      </div>`,
    plain: text.trim(),
    timestamp: new Date().toISOString(),
  };
}

/**
 * WhatsApp — respect character limits and formatting rules.
 */
function formatForWhatsApp(text, metadata) {
  // WhatsApp has a 4096 character limit per message
  const chunks = splitIntoChunks(text, 4000);

  return {
    type: 'whatsapp',
    messages: chunks.map(chunk => ({
      text: chunk.trim(),
    })),
    timestamp: new Date().toISOString(),
  };
}

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Split text into chunks at sentence boundaries.
 */
function splitIntoChunks(text, maxLength) {
  if (text.length <= maxLength) return [text];

  const chunks = [];
  let remaining = text;

  while (remaining.length > maxLength) {
    let splitAt = remaining.lastIndexOf('. ', maxLength);
    if (splitAt === -1 || splitAt < maxLength * 0.5) {
      splitAt = remaining.lastIndexOf(' ', maxLength);
    }
    if (splitAt === -1) splitAt = maxLength;

    chunks.push(remaining.slice(0, splitAt + 1));
    remaining = remaining.slice(splitAt + 1).trimStart();
  }

  if (remaining.length > 0) chunks.push(remaining);
  return chunks;
}

/**
 * Escape HTML special characters.
 */
function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Redact PII from text for logging.
 */
export function redactPII(text) {
  if (!text) return text;
  return text
    .replace(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g, '[EMAIL]')
    .replace(/(?:\+?\d{1,3}[-.\s]?)?\(?\d{2,4}\)?[-.\s]?\d{3,4}[-.\s]?\d{3,4}/g, '[PHONE]')
    .replace(/\b\d{13,19}\b/g, '[CARD]');
}

export default { formatResponse, redactPII };
